config/routes.rb
require 'sidekiq/web'


Rails.application.routes.draw do


  mount Sidekiq::Web, at: '/sidekiq'
  resources :documents, only: :show, path: 'doc' do
    get 'download/:id' => 'downloads#show', as: :download
  end
  get 'search/autocomplete' => 'searches#autocomplete'
  get 'search' => 'searches#show'
  get 'account/:id' => 'accounts#show', as: :account
  post 'comments/new' => 'comments#new'

  root 'home#index'

  namespace :auth do
    scope :accounts do
      root 'accounts#index'
      get 'log_in' => 'accounts#log_in', as: 'log_in_session'
      post 'log_in' => 'accounts#do_log_in'
      delete 'log_out' => 'accounts#log_out', as: 'log_out_session'
      get 'register' => 'accounts#register', as: 'register_account'
      post 'register' => 'accounts#do_register'
      get 'activate/:id' => 'accounts#activate', as: 'activate_account'
      get 'forgot' => 'accounts#forgot', as: 'forgot_password_account'
      post 'forgot' => 'accounts#do_forgot'
      get 'reset/:id' => 'accounts#reset', as: 'reset_password_account'
      post 'reset/:id' => 'accounts#do_reset'
    end
    namespace :admin do
      root 'admin#index'
      resources :documents
      resources :categories
    end

    namespace :staff do
      root 'staff#index'
      resources :accounts do
        get 'ban' => 'accounts#ban_account'
      end
    end
    resources :documents, path_names: {new: 'new/step-1'} do
      delete 'downloads/:id' => 'downloads#destroy', as: :download
    end
    get 'documents/new/:id/step-2' => 'documents#step_2', as: :documents_new_step_2
    post 'downloads' => 'downloads#create'

  end

end

app/models/document.rb
class Document < ActiveRecord::Base
  searchkick callbacks: :async, autocomplete: [:title], highlight: {tag: "<strong>"}
  extend FriendlyId

  belongs_to :category
  belongs_to :uploader, class_name: 'Account'
  belongs_to :lang

  validates :title, presence: true
  validates :tags, presence: true

  has_many :downloads, dependent: :destroy
  has_many :comments, dependent: :destroy

  accepts_nested_attributes_for :downloads, allow_destroy: true

  friendly_id :title, use: [:slugged, :finders]
  has_attached_file :image

  def self.title_is(title)
    sensitive = where(:title => title.strip).limit(1)
    return sensitive unless sensitive.empty?
    where("UPPER(title) = UPPER(?)", title.strip).take
  end

  def to_param
    slug
  end

  def to_s
    title
  end

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController


  before_filter :auth_account

  def show
    @document = Document.friendly.find(params[:id])
    @document.views += 1
    @document.save
  end
  
end

app/helpers/document_helper.rb
module DocumentHelper
end

app/views/documents/show.html.haml
- provide(:title, @document.title)
- provide(:keywords, @document.tags)
- provide(:description, truncate(@document.description, separator: ' '))

%h2= @document.title

%p
  %b
    = t('description')
    %br
  = @document.description
%p
  %b
    = t(:category)
    %br
  = @document.category
%p
  %b #{t('uploader')}:
  #{link_to @document.uploader, @document.uploader}


%h3= t('download_section')
= t('this_file_has_been_downloaded_over_n_times', n: @document.downloads.sum(:download_counter))
%table.fullWidth
  %thead
    %tr
      %th= t('name')
      %th= t('file_type')
      %th= t('size')
  %tbody
    - @document.downloads.each do |download|
      - cache(download) do
        %tr
          %td= link_to download.download_file_name, document_download_path(document_id: @document.id, id: download.id)
          %td= download.download_content_type
          %td= number_to_human_size(download.download_file_size)

%h3= t('comments')
.comments
  - comment_number = 1
  - @document.comments.each do |comment|
    .comment-box
      \##{comment_number}
      .comment-body
        = comment.body
      .comment-author{id: "comment_#{comment_number}"}
        %a#comment{id: comment_number}= t('answer_comment')
        = comment.account
        - if comment.account == @document.uploader
          %i (#{t('uploader')})
        - elsif comment.account.staff?
          %i (#{t('staff')})
        - elsif comment.account.admin?
          %i (#{t('admin')})
      - if comment.response
        .comment-box
          = comment.body
        .comment-author
          = comment.account
    - comment_number += 1
.create-comment
  = render 'comments/new'