config/routes.rb
require 'sidekiq/web'


Rails.application.routes.draw do


  mount Sidekiq::Web, at: '/sidekiq'
  resources :documents, only: :show, path: 'doc' do
    get 'download/:id' => 'downloads#show', as: :download
  end
  get 'search/autocomplete' => 'searches#autocomplete'
  get 'search' => 'searches#show'
  get 'account/:id' => 'accounts#show', as: :account
  post 'comments/new' => 'comments#new'

  root 'home#index'

  namespace :auth do
    scope :accounts do
      root 'accounts#index'
      get 'log_in' => 'accounts#log_in', as: 'log_in_session'
      post 'log_in' => 'accounts#do_log_in'
      delete 'log_out' => 'accounts#log_out', as: 'log_out_session'
      get 'register' => 'accounts#register', as: 'register_account'
      post 'register' => 'accounts#do_register'
      get 'activate/:id' => 'accounts#activate', as: 'activate_account'
      get 'forgot' => 'accounts#forgot', as: 'forgot_password_account'
      post 'forgot' => 'accounts#do_forgot'
      get 'reset/:id' => 'accounts#reset', as: 'reset_password_account'
      post 'reset/:id' => 'accounts#do_reset'
    end
    namespace :admin do
      root 'admin#index'
      resources :documents
      resources :categories
    end

    namespace :staff do
      root 'staff#index'
      resources :accounts do
        get 'ban' => 'accounts#ban_account'
      end
    end
    resources :documents, path_names: {new: 'new/step-1'} do
      delete 'downloads/:id' => 'downloads#destroy', as: :download
    end
    get 'documents/new/:id/step-2' => 'documents#step_2', as: :documents_new_step_2
    post 'downloads' => 'downloads#create'

  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    if params[:query]
      @results = Document.search(params[:query], page: params[:page], per_page: 20, highlight: true, fields: [:title, :description])
      @exact_match = Document.title_is(params[:query])

      redirect_to @exact_match if @results == [@exact_match]
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/searches/show.html.haml
- provide(:title, t('search_results_for_n', n: params[:query]))

= render 'layouts/search'

- unless @results.empty?
  - @results.each do |result|
    .search-result
      %h2= link_to result.title, result
      %div= truncate(result.description)
      %summary
        = t(:created_date_ago, date: time_ago_in_words(result.created_at))
        = t(:by_uploader_html, uploader: link_to(result.uploader, account_path(result.uploader)))
        = t(:in_category_html, category: result.category)

  = paginate @results
- else
  #{t(:n_results_found, count: 0)}