config/routes.rb
require 'sidekiq/web'


Rails.application.routes.draw do


  mount Sidekiq::Web, at: '/sidekiq'
  resources :documents, only: :show, path: 'doc' do
    get 'download/:id' => 'downloads#show', as: :download
  end
  get 'search/autocomplete' => 'searches#autocomplete'
  get 'search' => 'searches#show'
  get 'account/:id' => 'accounts#show', as: :account
  post 'comments/new' => 'comments#new'

  root 'home#index'

  namespace :auth do
    scope :accounts do
      root 'accounts#index'
      get 'log_in' => 'accounts#log_in', as: 'log_in_session'
      post 'log_in' => 'accounts#do_log_in'
      delete 'log_out' => 'accounts#log_out', as: 'log_out_session'
      get 'register' => 'accounts#register', as: 'register_account'
      post 'register' => 'accounts#do_register'
      get 'activate/:id' => 'accounts#activate', as: 'activate_account'
      get 'forgot' => 'accounts#forgot', as: 'forgot_password_account'
      post 'forgot' => 'accounts#do_forgot'
      get 'reset/:id' => 'accounts#reset', as: 'reset_password_account'
      post 'reset/:id' => 'accounts#do_reset'
    end
    namespace :admin do
      root 'admin#index'
      resources :documents
      resources :categories
    end

    namespace :staff do
      root 'staff#index'
      resources :accounts do
        get 'ban' => 'accounts#ban_account'
      end
    end
    resources :documents, path_names: {new: 'new/step-1'} do
      delete 'downloads/:id' => 'downloads#destroy', as: :download
    end
    get 'documents/new/:id/step-2' => 'documents#step_2', as: :documents_new_step_2
    post 'downloads' => 'downloads#create'

  end

end

app/models/account.rb
class Account < ActiveRecord::Base
  extend FriendlyId
  has_secure_password

  friendly_id :user_name, use: [:slugged, :finders]

  validates :email, presence: true, uniqueness: true
  validates :user_name, presence: true, uniqueness: true

  has_many :documents, foreign_key: 'uploader_id'
  has_many :comments

  before_save {
    self.email = email.downcase
  }

  def to_s
    user_name || email
  end

  def admin?
    rank == 4
  end

  def premium?
    rank == 2
  end

  def staff?
    rank >= 3
  end

  def self.new_session_token
    SecureRandom.urlsafe_base64
  end 

  def self.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def to_param
    user_name.parameterize
  end


  private
    def create_session_token
      self.session_token = self.digest(self.new_session_token)
    end

end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId
  belongs_to :category_parent, class_name: 'Category'

  translates :name
  has_many :documents

  friendly_id :name, use: [:slugged, :finders]
  has_many :category_children, class_name: 'Category',
    foreign_key: 'category_parent_id'

  def to_s
    name
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :document
  belongs_to :account

  belongs_to :response

  validates :body, presence: true

end

app/models/document.rb
class Document < ActiveRecord::Base
  searchkick callbacks: :async, autocomplete: [:title], highlight: {tag: "<strong>"}
  extend FriendlyId

  belongs_to :category
  belongs_to :uploader, class_name: 'Account'
  belongs_to :lang

  validates :title, presence: true
  validates :tags, presence: true

  has_many :downloads, dependent: :destroy
  has_many :comments, dependent: :destroy

  accepts_nested_attributes_for :downloads, allow_destroy: true

  friendly_id :title, use: [:slugged, :finders]
  has_attached_file :image

  def self.title_is(title)
    sensitive = where(:title => title.strip).limit(1)
    return sensitive unless sensitive.empty?
    where("UPPER(title) = UPPER(?)", title.strip).take
  end

  def to_param
    slug
  end

  def to_s
    title
  end

end

app/models/download.rb
class Download < ActiveRecord::Base
  belongs_to :document

  has_attached_file :download

  validates_attachment_content_type :download, content_type: /\Aapplication\/pdf\Z/
end

app/models/lang.rb
class Lang < ActiveRecord::Base

  has_many :documents

end

app/models/token.rb
class Token < ActiveRecord::Base
  belongs_to :account

  def self.create_confirmation_token account
    begin
      token = self.random_string(30)
    end while self.exists?(token: token)
    create(account: account, token: token, confirmation: true)
    token
  end

  def self.create_resetting_token account
    begin
      token = self.random_string(30)
    end while self.exists?(token: token)
    create(account: account, token: token, reset: true)
    token
  end

  def self.random_string(length, include_uppercase = true, include_lowercase = true, include_numbers = false)
    o = []
    o.push ('a'..'z') if include_uppercase
    o.push ('A'..'Z') if include_lowercase
    
    o.push (0..9) if include_numbers
    o = o.map { |i| i.to_a }.flatten
    (0...length).map { o[rand(o.length)] }.join
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def show
    @account = Account.friendly.find(params[:id])
    @documents = Document.where(uploader: @account).order(:created_at).limit(5)
    @comments = Comment.where(account: @account).order(:created_at).limit(5)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController 

  before_filter :auth_account

  def new
    comment = Comment.new(comment_params)
    comment.account = current_account
    comment.sender_ip = request.remote_ip
    comment.sender_hostname = Resolv.getname(comment.sender_ip)

    if comment.save
      flash.now[:success] = I18n.t('comment_successfully_created')
    else
      flash.now[:error] = I18n.t('error_while_proceeding_save_comment')
    end
    redirect_to comment.document
  end

  private
    def comment_params
      params.require(:comment).permit(:body, :document_id)
    end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController


  before_filter :auth_account

  def show
    @document = Document.friendly.find(params[:id])
    @document.views += 1
    @document.save
  end
  
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController

  before_filter :auth_account

  def show
    @download = Download.find(params[:id])
    @download.download_counter += 1
    @download.save

    send_data File.read(@download.download.path),
          :type => "#{@download.download_content_type}; charset=UTF-8;",
              :disposition => "attachment; filename=#{@download.download_file_name}"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    if params[:query]
      @results = Document.search(params[:query], page: params[:page], per_page: 20, highlight: true, fields: [:title, :description])
      @exact_match = Document.title_is(params[:query])

      redirect_to @exact_match if @results == [@exact_match]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper

  def generate_tree
    @parent_categories = Category.where(category_parent: nil)
    nesting_tree(@parent_categories)
  end

  private
    def nesting_tree leaves
      render = "<ul>"

      leaves.each do |leaf|
        render += "<li>" + leaf.name
        render += nesting_tree(leaf.category_children) unless leaf.category_children.empty?
        render += "</li>"
      end

      return render + "</ul>"
    end
end

app/helpers/document_helper.rb
module DocumentHelper
end

app/helpers/download_helper.rb
module DownloadHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in (account, remember = "0")
    session_token = Account.new_session_token
    if remember == "1"
      cookies.permanent.signed[:session_token] = session_token
    else
      cookies.signed[:session_token] = session_token
    end

    account.update_attribute(:session_token, Account.digest(session_token))
    self.current_account = account
  end

  def sign_out
    current_account.update_attribute(:session_token, Account.new_session_token)
    cookies.delete(:session_token)
    self.current_account = nil
  end

  def signed_in?
    !current_account.nil?
  end

  def current_account=(account)
    @current_account = account
  end

  def current_account
    session_token = Account.digest(cookies.signed[:session_token])
    @current_account ||= Account.find_by(session_token: session_token)
  end
end

app/views/layouts/_cookies.html.haml
.hidden.about_cookies
  .text
    = t('about_cookies')
  %a.close_cookies_button
    = image_tag 'close_button.png'

app/views/layouts/_footer.html.haml
%footer
  #container
    %div
      %span.company
        Sortahole
      &copy; #{Time.now.year}
    All rights reserved

app/views/layouts/_nav.html.haml
%nav.top-bar{data: {topbar: true}, role: 'navigation'}
  %ul.title-area
    %li.name
      %h1
        %a{href: "/"} Documentation
  %section.top-bar-section.navigation
    %ul.right
      %li=link_to t('discuss'), '#'
      - if signed_in?
        %li.has-dropdown
          =link_to t('documents'), auth_documents_path
          %ul.dropdown
            %li= link_to t('create'), new_auth_document_path
        %li.has-dropdown
          =link_to current_account.user_name, '#'
          %ul.dropdown
            %li= link_to t('dashboard'), auth_root_path
            - if current_account.admin?
              %li= link_to t('admin'), auth_admin_root_path  
            - if current_account.staff?
              %li= link_to t('staff'), auth_staff_root_path
            %li
              = link_to t('log_out'), auth_log_out_session_path, method: :delete
      - else
        %li
          = link_to t('log_in'), auth_log_in_session_path
        %li.has-form
          = link_to t('register'), auth_register_account_path, class: 'button'

app/views/layouts/_search.html.haml
= form_tag({controller: 'searches', action: 'show'}, method: :get, class: 'search-bar') do
  .row
    .large-12.columns
      .row.collapse
        .large-10.columns
          = search_field_tag :query, nil, required: true, autofocus: true, placeholder: t(:search_documents), value: params[:query]
        .large-2.columns
          = button_tag nil, name: nil do
            %i.fa.fa-search

app/views/layouts/application.html.haml
!!! html
%html
  %head
    %meta{name: "description", content: "#{yield :description}"}
    %meta{name: "keywords", content: "#{yield :keywords}"}
    %title #{yield :title} - Documentation
    = stylesheet_link_tag    'https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css', media: 'all'
    = stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag    'http://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext', media: 'all'
    = csrf_meta_tags
  %body
    = render 'layouts/nav'
    %section
      .row.realFullWidth
        .large-2.columns
          &nbsp;
        .large-8.columns
          - flash.each do |type, message|
            .alert-box.radius{data: {alert: true}, class: type}
              = message
              %a.close{href: "#"} &times;
          = yield
        .large-2.columns
          &nbsp;
    = render 'layouts/footer'
    = render 'layouts/cookies'
    = piwik_tracking_tag
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/layouts/home.html.haml
!!! html
%html.no-js
  %head
    %meta{name:"viewport", content: "width=device-width, initial-scale=1.0"}
    %meta{name:"description", content: ""}
    %meta{name:"keywords", content: ""}
    %title Documentation
    = stylesheet_link_tag    'https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css', media: 'all'
    = stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'
    = stylesheet_link_tag    'home', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag    'http://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext', media: 'all'
    = javascript_include_tag :modernizr
    = csrf_meta_tags
  %body
    %section#top
      = render 'layouts/nav'
      .row
        .large-3.columns &nbsp;
        .large-6.columns
          - flash.each do |type, message|
            .alert-box.radius{data: {alert: true}, class: type}
              = message
              %a.close{href: "#"} &times;
          #search
            = yield
        .large-3.columns &nbsp;
    %section#company
      .row
        .large-9.columns.info
          %h2 What is it about?
          %p
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam in egestas nulla. Maecenas vel fringilla nisi, ac vestibulum lacus. Morbi metus ligula, auctor id sem non, aliquam feugiat orci. Donec sagittis lobortis tellus, vitae interdum ante faucibus eu. Curabitur id nulla elit. Cras cursus lectus ante, eu convallis lacus viverra at. Nunc ut sagittis tortor, ut tempor quam. Curabitur ac tempor diam. Sed non dolor gravida, sagittis tortor sit amet, dapibus nulla. Sed consequat imperdiet quam fermentum dapibus. Aenean in lacus vehicula, tempor metus convallis, maximus justo. Nulla luctus gravida tristique.
          %p
            Donec dolor sem, tincidunt sit amet mauris tincidunt, pulvinar facilisis ante. In aliquam, lacus mattis interdum pellentesque, turpis sem volutpat metus, sed efficitur velit dui et ex. Quisque ut ultrices magna. Fusce rutrum varius laoreet. Proin sed lacus est. Donec lobortis eget metus id tempus. Nulla tristique nibh elit, in dignissim risus eleifend a. Sed tincidunt ac nunc id elementum. Cras in metus diam. Integer eget sodales urna. Nulla volutpat sollicitudin est, sed laoreet erat sollicitudin pellentesque. Vestibulum scelerisque sed lorem sit amet auctor.

        .large-3.columns.side-info
          %p
            - cache expires_in: 1.hour do
              = t(:n_documents_html, count: Document.count)
          %p
            - cache 'amount_of_categories_cache' do
              = t(:n_categories_html, count: Category.count)
    = render 'layouts/footer'
    = render 'layouts/cookies'
    = piwik_tracking_tag
    = javascript_include_tag 'home', 'data-turbolinks-track' => true